//
// Generated file, do not edit! Created by opp_msgtool 6.0 from veins/modules/application/Thesis_src/messages/mixZoneAd.msg.
//

#ifndef __VEINS_MIXZONEAD_M_H
#define __VEINS_MIXZONEAD_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif


namespace veins {

class mixZoneAd;

}  // namespace veins

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress

#include "veins/modules/messages/DemoSafetyMessage_m.h" // import veins.modules.messages.DemoSafetyMessage


namespace veins {

/**
 * Class generated from <tt>veins/modules/application/Thesis_src/messages/mixZoneAd.msg:6</tt> by opp_msgtool.
 * <pre>
 * packet mixZoneAd extends DemoSafetyMessage
 * {
 *     int mixZoneID;
 * }
 * </pre>
 */
class VEINS_API mixZoneAd : public ::veins::DemoSafetyMessage
{
  protected:
    int mixZoneID = 0;

  private:
    void copy(const mixZoneAd& other);

  protected:
    bool operator==(const mixZoneAd&) = delete;

  public:
    mixZoneAd(const char *name=nullptr, short kind=0);
    mixZoneAd(const mixZoneAd& other);
    virtual ~mixZoneAd();
    mixZoneAd& operator=(const mixZoneAd& other);
    virtual mixZoneAd *dup() const override {return new mixZoneAd(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getMixZoneID() const;
    virtual void setMixZoneID(int mixZoneID);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const mixZoneAd& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, mixZoneAd& obj) {obj.parsimUnpack(b);}


}  // namespace veins


namespace omnetpp {

template<> inline veins::mixZoneAd *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::mixZoneAd*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __VEINS_MIXZONEAD_M_H

